### ISSUE TITLE
Device-virtual got crash sometimes

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/device-virtual-go#111]
When creating device with autoEvents, device-virtual got crash sometimes.

Post data:
```
POST Request using : uri=/api/v1/device, params=None, files=None, allow_redirects=True, timeout=None
headers={'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json'} 
data={
   "origin":1471806386919,
   "name" :"AutoEvent-Device",
   "description":"AutoEvent-Device",
   "adminState":"UNLOCKED",
   "operatingState":"ENABLED",
   "protocols":{
      "other":{
         "Address"  : "simple01",
          "Port" : "300"
      }
   },
   "labels":[
      "device-example"
   ],
   "location":"{lat:45.45,long:47.80}",
   "responseDelay":0,
   "service":{
      "name":"device-virtual"
   },
   "profile":{
      "name":"Sample-Profile"
   },
   "autoEvents":[
      {
         "frequency":"8s",
         "onChange":false,
         "resource":"DeviceValue_FLOAT32_W"
      }
   ]
   
}
```
The resource only allows to use put command.

Error logs:
```
level=INFO ts=2020-05-13T09:12:26.715522171Z app=device-virtual source=device.go:58 msg="Added device: AutoEvent-Device"
panic: strconv: illegal AppendFloat/FormatFloat bitSize

goroutine 8468232 [running]:
strconv.genericFtoa(0xc00059e6a0, 0x0, 0x18, 0x0, 0xc000084065, 0xffffffffffffffff, 0x0, 0x51e6fa, 0xc00000c060, 0x160e8b8cd4e17834)
	/usr/local/go/src/strconv/ftoa.go:68 +0x914
strconv.FormatFloat(0x0, 0x65, 0xffffffffffffffff, 0x0, 0xc00031a010, 0x6)
	/usr/local/go/src/strconv/ftoa.go:48 +0xa7
github.com/edgexfoundry/device-virtual-go/internal/driver.(*resourceFloat).value(0xeec0c8, 0xc000368480, 0xc000413360, 0x10, 0xc00016ca20, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/edgexfoundry/device-virtual-go/internal/driver/resourcefloat.go:61 +0x3ae
github.com/edgexfoundry/device-virtual-go/internal/driver.(*virtualDevice).read(0xc0001106c0, 0xc000413360, 0x10, 0xc00016ca20, 0x15, 0xc000413726, 0x7, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/edgexfoundry/device-virtual-go/internal/driver/virtualdevice.go:49 +0x42e
github.com/edgexfoundry/device-virtual-go/internal/driver.(*VirtualDriver).HandleReadCommands(0xc00008c5f0, 0xc000413360, 0x10, 0xc00035eb70, 0xc0002d4f40, 0x1, 0x1, 0xc00000e8d8, 0x1, 0x1, ...)
	/go/src/github.com/edgexfoundry/device-virtual-go/internal/driver/virtualdriver.go:111 +0x42d
github.com/edgexfoundry/device-sdk-go/internal/handler.execReadDeviceResource(0xc000377870, 0xc000377718, 0x0, 0x0, 0x15, 0xc00016ca00, 0x1d)
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0/internal/handler/command.go:116 +0x2c5
github.com/edgexfoundry/device-sdk-go/internal/handler.CommandHandler(0xc0001d5bd8, 0x0, 0x0, 0xa5d15c, 0x3, 0x0, 0x0, 0x7f238211a448, 0xc000229bf0, 0x40bc24)
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0/internal/handler/command.go:83 +0x455
github.com/edgexfoundry/device-sdk-go/internal/autoevent.readResource(0xc0000b8000, 0xc0000220a0, 0x4b, 0x0)
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0/internal/autoevent/executor.go:87 +0x182
github.com/edgexfoundry/device-sdk-go/internal/autoevent.(*executor).Run(0xc0000b8000, 0xb40240, 0xc00010ef00, 0xc00012a890)
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0/internal/autoevent/executor.go:50 +0x242
created by github.com/edgexfoundry/device-sdk-go/internal/autoevent.triggerExecutors
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0/internal/autoevent/manager.go:72 +0x1da 
```

**Comment by tonyespy** [comment]
@cloudxxx8 @cherrycl what version of device-virtual? FYI, labels are supposed to be used to indicate the release of EdgeX the issue was discovered in, not the release it's slated to be fixed in.

**Comment by cloudxxx8** [comment]
@cherrycl please help confirm whether this issue still exists, thanks

**Comment by cherrycl** [comment]
Close issue since the issue does not exist.
