### ISSUE TITLE
Unclean shutdown if required services are not healthy

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/device-virtual-go#97]
While bringing up stack with docker-compose-nexus-redis.yml

```
docker logs -f edgex-device-virtual
level=INFO ts=2020-04-21T21:42:08.643919837Z app=device-virtual source=config.go:219 msg="Loaded configuration from /res/configuration.toml"
level=INFO ts=2020-04-21T21:42:08.644518414Z app=device-virtual source=environment.go:264 msg="Environment override of 'Clients.Metadata.Host' by environment variable: Clients_Metadata_Host=edgex-core-metadata"
level=INFO ts=2020-04-21T21:42:08.644537556Z app=device-virtual source=environment.go:264 msg="Environment override of 'Registry.Host' by environment variable: Registry_Host=edgex-core-consul"
level=INFO ts=2020-04-21T21:42:08.64454924Z app=device-virtual source=environment.go:264 msg="Environment override of 'Service.Host' by environment variable: Service_Host=edgex-device-virtual"
level=INFO ts=2020-04-21T21:42:08.644555199Z app=device-virtual source=environment.go:264 msg="Environment override of 'Clients.Logging.Host' by environment variable: Clients_Logging_Host=edgex-support-logging"
level=INFO ts=2020-04-21T21:42:08.644715262Z app=device-virtual source=config.go:167 msg="Using Configuration provider (consul) from: http://edgex-core-consul:8500 with base path of edgex/core/1.0/device-virtual"
level=INFO ts=2020-04-21T21:42:09.60539983Z app=device-virtual source=config.go:321 msg="Configuration has been pushed to into Configuration Provider (4 environment overrides applied)"
level=ERROR ts=2020-04-21T21:42:09.605510952Z app=device-virtual source=logger.go:74 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2020-04-21T21:42:09.605550586Z app=device-virtual source=registry.go:79 msg="Using Registry (consul) from http://edgex-core-consul:8500"
level=INFO ts=2020-04-21T21:42:09.606398784Z app=device-virtual source=config.go:308 msg="Writeable configuration has been updated from the Configuration Provider"
level=INFO ts=2020-04-21T21:42:09.639755651Z app=device-virtual source=httpserver.go:89 msg="Web server starting (edgex-device-virtual:49990)"
level=INFO ts=2020-04-21T21:42:09.639863359Z app=device-virtual source=init.go:134 msg="Check Metadata service's status via Registry..."
level=INFO ts=2020-04-21T21:42:09.640031109Z app=device-virtual source=init.go:134 msg="Check Data service's status via Registry..."
level=ERROR ts=2020-04-21T21:42:09.643088524Z app=device-virtual source=init.go:149 msg=" edgex-core-metadata service not healthy..."
level=ERROR ts=2020-04-21T21:42:09.643133383Z app=device-virtual source=init.go:149 msg=" edgex-core-data service not healthy..."
level=INFO ts=2020-04-21T21:42:14.643529931Z app=device-virtual source=init.go:134 msg="Check Data service's status via Registry..."
level=INFO ts=2020-04-21T21:42:14.643692179Z app=device-virtual source=init.go:134 msg="Check Metadata service's status via Registry..."
level=ERROR ts=2020-04-21T21:42:14.646774235Z app=device-virtual source=init.go:149 msg=" edgex-core-metadata service not healthy..."
level=ERROR ts=2020-04-21T21:42:14.647093712Z app=device-virtual source=init.go:149 msg=" edgex-core-data service not healthy..."
level=INFO ts=2020-04-21T21:42:19.647325747Z app=device-virtual source=init.go:134 msg="Check Data service's status via Registry..."
level=INFO ts=2020-04-21T21:42:19.647336809Z app=device-virtual source=init.go:134 msg="Check Metadata service's status via Registry..."
level=ERROR ts=2020-04-21T21:42:19.650459979Z app=device-virtual source=init.go:149 msg=" edgex-core-metadata service not healthy..."
level=ERROR ts=2020-04-21T21:42:24.651046495Z app=device-virtual source=init.go:112 msg="service dependency Metadata checking time out"
level=INFO ts=2020-04-21T21:42:24.651187559Z app=device-virtual source=httpserver.go:106 msg="Web server shutting down"
error: checking required dependencied services failed 
level=INFO ts=2020-04-21T21:42:24.65125467Z app=device-virtual source=httpserver.go:108 msg="Web server shut down"
level=INFO ts=2020-04-21T21:42:24.651267689Z app=device-virtual source=httpserver.go:97 msg="Web server stopped"
level=INFO ts=2020-04-21T21:42:24.651376688Z app=device-virtual source=bootstrap.go:130 msg="Un-Registering service from the Registry"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x92e2d9]

goroutine 1 [running]:
github.com/edgexfoundry/device-virtual-go/internal/driver.(*VirtualDriver).Stop(0xc0000945f0, 0xc000561f00, 0x1, 0xc0001348f0)
	/go/src/github.com/edgexfoundry/device-virtual-go/internal/driver/virtualdriver.go:156 +0x29
github.com/edgexfoundry/device-sdk-go/pkg/service.(*Service).Stop(0xc000116600, 0xc000117000)
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/pkg/service/service.go:67 +0x3e
github.com/edgexfoundry/device-sdk-go/pkg/service.Main(0xa5bb7b, 0xe, 0xb21d20, 0xb, 0xa02d60, 0xc0000945f0, 0xb3af80, 0xc000117080, 0xc0000e4fc0, 0xc00011e540, ...)
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/pkg/service/main.go:81 +0x6f0
github.com/edgexfoundry/device-sdk-go/pkg/startup.Bootstrap(0xa5bb7b, 0xe, 0xb21d20, 0xb, 0xa02d60, 0xc0000945f0)
	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/pkg/startup/bootstrap.go:19 +0x112
main.main()
	/go/src/github.com/edgexfoundry/device-virtual-go/cmd/main.go:21 +0x6f
```

**Comment by cloudxxx8** [comment]
this should belong to SDK

**Comment by hahattan** [comment]
the reason is that `driver.Stop` is called before `driver.Initilaize`, suggests to refactor the `BootstrapHandler` in SDK again to move `driver.Initialize` in the beginning 
 (e.g. after `svc = newService(dic)`):
https://github.com/edgexfoundry/device-sdk-go/blob/dfaaf3db4a48c41e92535fbbc26dffa7770b5bf3/pkg/service/init.go#L43

**Comment by hahattan** [comment]
I've upgraded to the latest SDK which should resolve this issue, please pull the master branch and help verify if it's resolved @bnevis-i

**Comment by cloudxxx8** [comment]
this issue still exists

**Comment by cloudxxx8** [comment]
I've verified this issue has gone by executing
docker-compose -f docker-compose-nexus-redis.yml up -d
